/**
 * Mock data fixtures for Engineering PM dashboard.
 * All data is in fa-IR where applicable; issue keys stay Latin (PM-101…).
 */

import type {
  Project,
  Issue,
  Member,
  Milestone,
  Cycle,
  PullRequest,
  Commit,
  ActivityEvent,
  Risk,
} from "@/components/features/types";

/* ── Members ─────────────────────────────────────────────────── */

export const members: Member[] = [
  {
    id: "m1",
    displayName: "سارا احمدی",
    avatarUrl: null,
    githubLogin: "sara-ahmadi",
  },
  {
    id: "m2",
    displayName: "علی محمدی",
    avatarUrl: null,
    githubLogin: "ali-mohammadi",
  },
  {
    id: "m3",
    displayName: "نیلوفر کریمی",
    avatarUrl: null,
    githubLogin: "niloofar-karimi",
  },
  {
    id: "m4",
    displayName: "محمد رضایی",
    avatarUrl: null,
    githubLogin: "mohammad-rezaei",
  },
  {
    id: "m5",
    displayName: "زهرا حسینی",
    avatarUrl: null,
    githubLogin: "zahra-hosseini",
  },
  {
    id: "m6",
    displayName: "امیر عباسی",
    avatarUrl: null,
    githubLogin: "amir-abbasi",
  },
];

/* ── Issues ──────────────────────────────────────────────────── */

export const issues: Issue[] = [
  {
    id: "i1",
    key: "PM-101",
    title: "پیاده‌سازی احراز هویت OAuth2",
    description: "افزودن ورود با گیت‌هاب و گوگل",
    status: "done",
    priority: "high",
    type: "feature",
    estimate: 8,
    dueDate: "2026-08-20",
    assignee: members[0],
    labels: [{ id: "l1", name: "backend", color: "#3b82f6" }],
    milestoneId: "ms1",
    cycleId: "c1",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-18T14:30:00Z",
    prCount: 2,
    prOpenCount: 0,
  },
  {
    id: "i2",
    key: "PM-102",
    title: "طراحی داشبورد مدیریت پروژه",
    description: "لایوت و کامپوننت‌های اصلی",
    status: "in_progress",
    priority: "high",
    type: "feature",
    estimate: 13,
    dueDate: "2026-09-15",
    assignee: members[2],
    labels: [
      { id: "l2", name: "frontend", color: "#8b5cf6" },
      { id: "l3", name: "design", color: "#ec4899" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-08-15T09:00:00Z",
    updatedAt: "2026-09-09T16:20:00Z",
    prCount: 1,
    prOpenCount: 1,
  },
  {
    id: "i3",
    key: "PM-103",
    title: "رفع باگ فرم ثبت‌نام",
    description: "اعتبارسنجی ایمیل کار نمی‌کند",
    status: "done",
    priority: "urgent",
    type: "bug",
    estimate: 3,
    dueDate: "2026-08-25",
    assignee: members[1],
    labels: [{ id: "l4", name: "bugfix", color: "#ef4444" }],
    milestoneId: "ms1",
    cycleId: "c1",
    createdAt: "2026-08-20T11:00:00Z",
    updatedAt: "2026-08-23T18:00:00Z",
    prCount: 1,
    prOpenCount: 0,
  },
  {
    id: "i4",
    key: "PM-104",
    title: "بهینه‌سازی کوئری‌های دیتابیس",
    description: "کاهش زمان پاسخ داشبورد",
    status: "in_review",
    priority: "medium",
    type: "improvement",
    estimate: 5,
    dueDate: "2026-09-10",
    assignee: members[3],
    labels: [{ id: "l1", name: "backend", color: "#3b82f6" }],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-08-25T08:30:00Z",
    updatedAt: "2026-09-08T10:15:00Z",
    prCount: 1,
    prOpenCount: 1,
  },
  {
    id: "i5",
    key: "PM-105",
    title: "پیاده‌سازی نوتیفیکیشن لحظه‌ای",
    description: "WebSocket برای اعلان‌های زنده",
    status: "todo",
    priority: "medium",
    type: "feature",
    estimate: 8,
    dueDate: "2026-09-20",
    assignee: members[0],
    labels: [
      { id: "l1", name: "backend", color: "#3b82f6" },
      { id: "l2", name: "frontend", color: "#8b5cf6" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-08-28T10:00:00Z",
    updatedAt: "2026-09-01T12:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i6",
    key: "PM-106",
    title: "تنظیم CI/CD پایپ‌لاین",
    description: "GitHub Actions برای تست و استقرار",
    status: "done",
    priority: "high",
    type: "chore",
    estimate: 5,
    dueDate: "2026-08-15",
    assignee: members[5],
    labels: [{ id: "l5", name: "devops", color: "#f59e0b" }],
    milestoneId: "ms1",
    cycleId: "c1",
    createdAt: "2026-08-05T14:00:00Z",
    updatedAt: "2026-08-14T09:00:00Z",
    prCount: 3,
    prOpenCount: 0,
  },
  {
    id: "i7",
    key: "PM-107",
    title: "تحقیق درباره کش توزیع‌شده",
    description: "مقایسه Redis و Memcached برای مقیاس‌پذیری",
    status: "backlog",
    priority: "low",
    type: "research",
    estimate: 5,
    dueDate: null,
    assignee: members[3],
    labels: [{ id: "l1", name: "backend", color: "#3b82f6" }],
    milestoneId: null,
    cycleId: null,
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i8",
    key: "PM-108",
    title: "بازطراحی صفحه پروفایل کاربر",
    description: "بهبود UX و افزودن آواتار",
    status: "todo",
    priority: "medium",
    type: "improvement",
    estimate: 5,
    dueDate: "2026-09-25",
    assignee: members[4],
    labels: [
      { id: "l2", name: "frontend", color: "#8b5cf6" },
      { id: "l3", name: "design", color: "#ec4899" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-02T09:00:00Z",
    updatedAt: "2026-09-05T11:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i9",
    key: "PM-109",
    title: "رفع باگ نمودار آماری",
    description: "داده‌های نادرست در نمودار هفتگی",
    status: "in_progress",
    priority: "high",
    type: "bug",
    estimate: 3,
    dueDate: "2026-09-12",
    assignee: members[2],
    labels: [
      { id: "l4", name: "bugfix", color: "#ef4444" },
      { id: "l2", name: "frontend", color: "#8b5cf6" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-03T14:00:00Z",
    updatedAt: "2026-09-09T17:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i10",
    key: "PM-110",
    title: "پیاده‌سازی جستجوی سراسری",
    description: "جستجو در پروژه‌ها، ایشوها و اعضا",
    status: "blocked",
    priority: "medium",
    type: "feature",
    estimate: 8,
    dueDate: "2026-09-18",
    assignee: members[1],
    labels: [
      { id: "l1", name: "backend", color: "#3b82f6" },
      { id: "l2", name: "frontend", color: "#8b5cf6" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-04T10:00:00Z",
    updatedAt: "2026-09-08T15:00:00Z",
    prCount: 1,
    prOpenCount: 1,
  },
  {
    id: "i11",
    key: "PM-111",
    title: "اتصال به اسلک",
    description: "اعلان‌ها و به‌روزرسانی خودکار وضعیت",
    status: "todo",
    priority: "low",
    type: "feature",
    estimate: 5,
    dueDate: "2026-10-01",
    assignee: null,
    labels: [{ id: "l5", name: "devops", color: "#f59e0b" }],
    milestoneId: "ms3",
    cycleId: null,
    createdAt: "2026-09-05T09:00:00Z",
    updatedAt: "2026-09-05T09:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i12",
    key: "PM-112",
    title: "مهاجرت به تیلویند ۴",
    description: "به‌روزرسانی کلاس‌ها و پلاگین‌ها",
    status: "in_progress",
    priority: "medium",
    type: "chore",
    estimate: 8,
    dueDate: "2026-09-22",
    assignee: members[4],
    labels: [{ id: "l2", name: "frontend", color: "#8b5cf6" }],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-05T11:00:00Z",
    updatedAt: "2026-09-10T08:30:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i13",
    key: "PM-113",
    title: "تست‌های واحد ماژول گزارش",
    description: "پوشش ۸۰٪ برای کامپوننت‌های گزارش",
    status: "todo",
    priority: "medium",
    type: "task",
    estimate: 5,
    dueDate: "2026-09-19",
    assignee: members[5],
    labels: [{ id: "l6", name: "testing", color: "#10b981" }],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-06T10:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i14",
    key: "PM-114",
    title: "تنظیم مانیتورینگ و لاگینگ",
    description: "Sentry و لاگ‌های ساختاریافته",
    status: "backlog",
    priority: "medium",
    type: "chore",
    estimate: 5,
    dueDate: null,
    assignee: null,
    labels: [
      { id: "l5", name: "devops", color: "#f59e0b" },
      { id: "l1", name: "backend", color: "#3b82f6" },
    ],
    milestoneId: "ms3",
    cycleId: null,
    createdAt: "2026-09-06T14:00:00Z",
    updatedAt: "2026-09-06T14:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i15",
    key: "PM-115",
    title: "بهبود عملکرد لود اولیه",
    description: "کاهش زمان TTFB به زیر ۲۰۰ms",
    status: "in_review",
    priority: "high",
    type: "improvement",
    estimate: 5,
    dueDate: "2026-09-11",
    assignee: members[0],
    labels: [
      { id: "l2", name: "frontend", color: "#8b5cf6" },
      { id: "l1", name: "backend", color: "#3b82f6" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-07T09:00:00Z",
    updatedAt: "2026-09-10T10:00:00Z",
    prCount: 1,
    prOpenCount: 1,
  },
  {
    id: "i16",
    key: "PM-116",
    title: "ایجاد API مستندات",
    description: "OpenAPI spec و Swagger UI",
    status: "done",
    priority: "medium",
    type: "task",
    estimate: 5,
    dueDate: "2026-09-01",
    assignee: members[3],
    labels: [{ id: "l1", name: "backend", color: "#3b82f6" }],
    milestoneId: "ms1",
    cycleId: "c1",
    createdAt: "2026-08-22T10:00:00Z",
    updatedAt: "2026-08-31T16:00:00Z",
    prCount: 1,
    prOpenCount: 0,
  },
  {
    id: "i17",
    key: "PM-117",
    title: "طراحی سیستم مجوزها",
    description: "RBAC با نقش‌های قابل تنظیم",
    status: "backlog",
    priority: "high",
    type: "feature",
    estimate: 13,
    dueDate: null,
    assignee: members[0],
    labels: [
      { id: "l1", name: "backend", color: "#3b82f6" },
      { id: "l7", name: "security", color: "#dc2626" },
    ],
    milestoneId: "ms3",
    cycleId: null,
    createdAt: "2026-09-08T09:00:00Z",
    updatedAt: "2026-09-08T09:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i18",
    key: "PM-118",
    title: "رفع باگ همگام‌سازی",
    description: "داده‌ها بعد از رفرش از بین می‌رود",
    status: "done",
    priority: "urgent",
    type: "bug",
    estimate: 3,
    dueDate: "2026-09-05",
    assignee: members[1],
    labels: [{ id: "l4", name: "bugfix", color: "#ef4444" }],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-04T11:00:00Z",
    updatedAt: "2026-09-06T18:00:00Z",
    prCount: 1,
    prOpenCount: 0,
  },
  {
    id: "i19",
    key: "PM-119",
    title: "افزودن حالت تاریک",
    description: "تم تاریک برای تمام صفحات",
    status: "cancelled",
    priority: "low",
    type: "improvement",
    estimate: 3,
    dueDate: null,
    assignee: null,
    labels: [{ id: "l2", name: "frontend", color: "#8b5cf6" }],
    milestoneId: null,
    cycleId: null,
    createdAt: "2026-08-10T10:00:00Z",
    updatedAt: "2026-09-01T09:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i20",
    key: "PM-120",
    title: "پیاده‌سازی فیلترهای پیشرفته",
    description: "فیلتر چندمعیاره برای لیست ایشوها",
    status: "in_progress",
    priority: "medium",
    type: "feature",
    estimate: 8,
    dueDate: "2026-09-20",
    assignee: members[2],
    labels: [
      { id: "l2", name: "frontend", color: "#8b5cf6" },
      { id: "l1", name: "backend", color: "#3b82f6" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-08T10:00:00Z",
    updatedAt: "2026-09-10T14:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i21",
    key: "PM-121",
    title: "تست بار سیستم",
    description: "Load test با k6 برای ۱۰۰۰ کاربر همزمان",
    status: "todo",
    priority: "medium",
    type: "task",
    estimate: 5,
    dueDate: "2026-09-28",
    assignee: members[5],
    labels: [
      { id: "l6", name: "testing", color: "#10b981" },
      { id: "l5", name: "devops", color: "#f59e0b" },
    ],
    milestoneId: "ms3",
    cycleId: null,
    createdAt: "2026-09-09T09:00:00Z",
    updatedAt: "2026-09-09T09:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i22",
    key: "PM-122",
    title: "رفع باگ RTL در فرم‌ها",
    description: "چیدمان فیلدها در حالت راست‌به‌چپ نادرست است",
    status: "in_progress",
    priority: "high",
    type: "bug",
    estimate: 2,
    dueDate: "2026-09-11",
    assignee: members[4],
    labels: [
      { id: "l4", name: "bugfix", color: "#ef4444" },
      { id: "l2", name: "frontend", color: "#8b5cf6" },
    ],
    milestoneId: "ms2",
    cycleId: "c2",
    createdAt: "2026-09-09T14:00:00Z",
    updatedAt: "2026-09-10T11:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i23",
    key: "PM-123",
    title: "ایجاد داشبورد مدیریت تیم",
    description: "نمایش حجم کار و ظرفیت اعضا",
    status: "todo",
    priority: "medium",
    type: "feature",
    estimate: 8,
    dueDate: "2026-10-05",
    assignee: null,
    labels: [
      { id: "l2", name: "frontend", color: "#8b5cf6" },
      { id: "l3", name: "design", color: "#ec4899" },
    ],
    milestoneId: "ms3",
    cycleId: null,
    createdAt: "2026-09-10T09:00:00Z",
    updatedAt: "2026-09-10T09:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i24",
    key: "PM-124",
    title: "بهبود مدیریت خطاها",
    description: "پیام‌های خطای کاربرپسند و صفحات ۴۰۴/۵۰۰",
    status: "backlog",
    priority: "low",
    type: "improvement",
    estimate: 3,
    dueDate: null,
    assignee: null,
    labels: [{ id: "l2", name: "frontend", color: "#8b5cf6" }],
    milestoneId: null,
    cycleId: null,
    createdAt: "2026-09-10T10:00:00Z",
    updatedAt: "2026-09-10T10:00:00Z",
    prCount: 0,
    prOpenCount: 0,
  },
  {
    id: "i25",
    key: "PM-125",
    title: "اتصال وب‌هوک گیت‌هاب",
    description: "همگام‌سازی خودکار PR و کامیت",
    status: "done",
    priority: "high",
    type: "feature",
    estimate: 5,
    dueDate: "2026-08-30",
    assignee: members[5],
    labels: [
      { id: "l1", name: "backend", color: "#3b82f6" },
      { id: "l5", name: "devops", color: "#f59e0b" },
    ],
    milestoneId: "ms1",
    cycleId: "c1",
    createdAt: "2026-08-18T10:00:00Z",
    updatedAt: "2026-08-29T17:00:00Z",
    prCount: 2,
    prOpenCount: 0,
  },
];

/* ── Milestones ──────────────────────────────────────────────── */

export const milestones: Milestone[] = [
  {
    id: "ms1",
    title: "نسخه آلفا",
    description: "نسخه اولیه با قابلیت‌های اصلی",
    status: "completed",
    targetDate: "2026-08-31",
    order: 1,
  },
  {
    id: "ms2",
    title: "نسخه بتا",
    description: "نسخه آزمایشی با بازخورد کاربران",
    status: "active",
    targetDate: "2026-09-30",
    order: 2,
  },
  {
    id: "ms3",
    title: "انتشار عمومی",
    description: "نسخه نهایی آماده تولید",
    status: "planned",
    targetDate: "2026-10-31",
    order: 3,
  },
];

/* ── Cycles ──────────────────────────────────────────────────── */

export const cycles: Cycle[] = [
  {
    id: "c1",
    name: "اسپرینت ۱",
    goal: "راه‌اندازی زیرساخت و احراز هویت",
    startDate: "2026-08-01",
    endDate: "2026-08-31",
    status: "completed",
    progress: 1,
    totalEstimate: 21,
    doneEstimate: 21,
  },
  {
    id: "c2",
    name: "اسپرینت ۲",
    goal: "داشبورد اصلی و قابلیت‌های تیم",
    startDate: "2026-09-01",
    endDate: "2026-09-28",
    status: "active",
    progress: 0.38,
    totalEstimate: 62,
    doneEstimate: 24,
  },
];

/* ── Pull Requests ───────────────────────────────────────────── */

export const pullRequests: PullRequest[] = [
  {
    id: "pr1",
    prNumber: 42,
    title: "feat: بهینه‌سازی کوئری‌های داشبورد",
    state: "open",
    authorLogin: "mohammad-rezaei",
    headBranch: "fix/dashboard-queries",
    baseBranch: "main",
    url: "https://github.com/org/eng-pm/pull/42",
    repoName: "eng-pm",
    createdAt: "2026-09-08T10:00:00Z",
    mergedAt: null,
    linkedIssues: ["PM-104"],
  },
  {
    id: "pr2",
    prNumber: 41,
    title: "feat: لایوت داشبورد مدیریت پروژه",
    state: "open",
    authorLogin: "niloofar-karimi",
    headBranch: "feat/project-dashboard",
    baseBranch: "main",
    url: "https://github.com/org/eng-pm/pull/41",
    repoName: "eng-pm",
    createdAt: "2026-09-07T14:00:00Z",
    mergedAt: null,
    linkedIssues: ["PM-102"],
  },
  {
    id: "pr3",
    prNumber: 40,
    title: "fix: همگام‌سازی داده‌ها بعد از رفرش",
    state: "merged",
    authorLogin: "ali-mohammadi",
    headBranch: "fix/data-sync",
    baseBranch: "main",
    url: "https://github.com/org/eng-pm/pull/40",
    repoName: "eng-pm",
    createdAt: "2026-09-05T11:00:00Z",
    mergedAt: "2026-09-06T16:30:00Z",
    linkedIssues: ["PM-118"],
  },
  {
    id: "pr4",
    prNumber: 39,
    title: "perf: بهبود TTFB و لود اولیه",
    state: "draft",
    authorLogin: "sara-ahmadi",
    headBranch: "perf/initial-load",
    baseBranch: "main",
    url: "https://github.com/org/eng-pm/pull/39",
    repoName: "eng-pm",
    createdAt: "2026-09-09T09:00:00Z",
    mergedAt: null,
    linkedIssues: ["PM-115"],
  },
  {
    id: "pr5",
    prNumber: 38,
    title: "feat: جستجوی سراسری",
    state: "open",
    authorLogin: "ali-mohammadi",
    headBranch: "feat/global-search",
    baseBranch: "main",
    url: "https://github.com/org/eng-pm/pull/38",
    repoName: "eng-pm",
    createdAt: "2026-09-06T10:00:00Z",
    mergedAt: null,
    linkedIssues: ["PM-110"],
  },
];

/* ── Commits ─────────────────────────────────────────────────── */

export const commits: Commit[] = [
  {
    id: "c1",
    sha: "a3f8e2d",
    message: "refactor: جدا کردن هوک‌های داشبورد",
    authorLogin: "niloofar-karimi",
    branch: "feat/project-dashboard",
    committedAt: "2026-09-10T09:15:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c2",
    sha: "b7c1d9a",
    message: "fix: اصلاح کوئری JOIN برای آمار",
    authorLogin: "mohammad-rezaei",
    branch: "fix/dashboard-queries",
    committedAt: "2026-09-10T08:45:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c3",
    sha: "e4f2c8b",
    message: "style: RTL فرم‌ها — اصلاح padding",
    authorLogin: "zahra-hosseini",
    branch: "fix/rtl-forms",
    committedAt: "2026-09-10T07:30:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c4",
    sha: "d9a3f1e",
    message: "feat: فیلتر چندمعیاره — UI نهایی",
    authorLogin: "niloofar-karimi",
    branch: "feat/advanced-filters",
    committedAt: "2026-09-09T18:00:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c5",
    sha: "c2b8e7f",
    message: "test: تست‌های API مستندات",
    authorLogin: "amir-abbasi",
    branch: "main",
    committedAt: "2026-09-09T15:20:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c6",
    sha: "f1d4a9c",
    message: "perf: lazy-load کامپوننت‌های سنگین",
    authorLogin: "sara-ahmadi",
    branch: "perf/initial-load",
    committedAt: "2026-09-09T12:10:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c7",
    sha: "a8c3e2b",
    message: "docs: به‌روزرسانی README",
    authorLogin: "amir-abbasi",
    branch: "main",
    committedAt: "2026-09-09T10:00:00Z",
    repoName: "eng-pm",
  },
  {
    id: "c8",
    sha: "b5f7d1a",
    message: "fix: باگ نمودار — تبدیل تاریخ شمسی",
    authorLogin: "niloofar-karimi",
    branch: "fix/chart-data",
    committedAt: "2026-09-08T16:45:00Z",
    repoName: "eng-pm",
  },
];

/* ── Activity Events ─────────────────────────────────────────── */

export const activityEvents: ActivityEvent[] = [
  {
    id: "a1",
    kind: "internal",
    verb: "status_change",
    entityType: "issue",
    actor: members[2],
    actorLogin: "niloofar-karimi",
    title: "PM-102 به «در حال انجام» تغییر کرد",
    createdAt: "2026-09-10T09:30:00Z",
  },
  {
    id: "a2",
    kind: "github",
    verb: "pr_opened",
    entityType: "pull_request",
    actor: members[3],
    actorLogin: "mohammad-rezaei",
    title: "PR #42 باز شد: بهینه‌سازی کوئری‌ها",
    createdAt: "2026-09-10T09:00:00Z",
  },
  {
    id: "a3",
    kind: "github",
    verb: "commit_pushed",
    entityType: "commit",
    actor: members[2],
    actorLogin: "niloofar-karimi",
    title: "کامیت a3f8e2d: جدا کردن هوک‌های داشبورد",
    createdAt: "2026-09-10T08:45:00Z",
  },
  {
    id: "a4",
    kind: "internal",
    verb: "assignee_change",
    entityType: "issue",
    actor: members[0],
    actorLogin: "sara-ahmadi",
    title: "PM-111 به «امیر عباسی» واگذار شد",
    createdAt: "2026-09-09T17:00:00Z",
  },
  {
    id: "a5",
    kind: "github",
    verb: "pr_merged",
    entityType: "pull_request",
    actor: members[1],
    actorLogin: "ali-mohammadi",
    title: "PR #40 مرج شد: همگام‌سازی داده‌ها",
    createdAt: "2026-09-09T16:30:00Z",
  },
  {
    id: "a6",
    kind: "internal",
    verb: "status_change",
    entityType: "issue",
    actor: members[1],
    actorLogin: "ali-mohammadi",
    title: "PM-118 به «تمام شده» تغییر کرد",
    createdAt: "2026-09-09T16:00:00Z",
  },
  {
    id: "a7",
    kind: "github",
    verb: "commit_pushed",
    entityType: "commit",
    actor: members[4],
    actorLogin: "zahra-hosseini",
    title: "کامیت e4f2c8b: RTL فرم‌ها",
    createdAt: "2026-09-09T15:00:00Z",
  },
  {
    id: "a8",
    kind: "internal",
    verb: "milestone_update",
    entityType: "milestone",
    actor: members[0],
    actorLogin: "sara-ahmadi",
    title: "وضعیت «نسخه آلفا» به «تحویل شده» تغییر کرد",
    createdAt: "2026-09-08T14:00:00Z",
  },
  {
    id: "a9",
    kind: "github",
    verb: "pr_opened",
    entityType: "pull_request",
    actor: members[2],
    actorLogin: "niloofar-karimi",
    title: "PR #41 باز شد: لایوت داشبورد پروژه",
    createdAt: "2026-09-08T12:00:00Z",
  },
  {
    id: "a10",
    kind: "internal",
    verb: "comment",
    entityType: "issue",
    actor: members[5],
    actorLogin: "amir-abbasi",
    title: "نظر جدید روی PM-110: «نیاز به Elasticsearch»",
    createdAt: "2026-09-08T10:30:00Z",
  },
  {
    id: "a11",
    kind: "github",
    verb: "commit_pushed",
    entityType: "commit",
    actor: members[0],
    actorLogin: "sara-ahmadi",
    title: "کامیت f1d4a9c: lazy-load کامپوننت‌ها",
    createdAt: "2026-09-07T18:00:00Z",
  },
  {
    id: "a12",
    kind: "internal",
    verb: "created",
    entityType: "issue",
    actor: members[0],
    actorLogin: "sara-ahmadi",
    title: "PM-123 ایجاد شد: داشبورد مدیریت تیم",
    createdAt: "2026-09-07T09:00:00Z",
  },
];

/* ── Risks ───────────────────────────────────────────────────── */

export const risks: Risk[] = [
  {
    id: "r1",
    kind: "blocked",
    title: "PM-110 بلاک شده — وابسته به Elasticsearch",
    detail: "جستجوی سراسری منتظر نصب و پیکربندی ES روی سرور staging",
    severity: "high",
    href: "/issues/PM-110",
  },
  {
    id: "r2",
    kind: "overdue",
    title: "PM-104 از موعد گذشته",
    detail: "تاریخ سررسید ۱۰ شهریور بود — هنوز در بازبینی",
    severity: "medium",
    href: "/issues/PM-104",
  },
  {
    id: "r3",
    kind: "stale_pr",
    title: "PR #38 بیش از ۴ روز بدون فعالیت",
    detail: "آخرین کامیت روی feat/global-search مربوط به ۶ شهریور",
    severity: "medium",
    href: "https://github.com/org/eng-pm/pull/38",
  },
  {
    id: "r4",
    kind: "unassigned",
    title: "۵ ایشو بدون مسئول",
    detail: "PM-111, PM-114, PM-123, PM-124, PM-119 هیچ اساینی ندارند",
    severity: "low",
    href: "/issues?assignee=none",
  },
  {
    id: "r5",
    kind: "deadline",
    title: "نسخه بتا — ۲۰ روز تا مهلت",
    detail: "۱۶ ایشو باز در اسپرینت ۲ باقی مانده — ریسک تأخیر",
    severity: "high",
    href: "/milestones/ms2",
  },
];

/* ── Projects ────────────────────────────────────────────────── */

export const projects: Project[] = [
  {
    id: "p1",
    key: "PM",
    name: "مدیریت مهندسی",
    description: "سیستم مدیریت پروژه و تسک برای تیم مهندسی",
    status: "active",
    health: "at_risk",
    targetDate: "2026-10-31",
    owner: members[0],
    teamName: "تیم مهندسی",
    progress: 0.42,
    healthReason: "اسپرینت ۲ عقب‌تر از برنامه — ۳ ایشو بلاک شده یا از موعد گذشته",
    counts: {
      todo: 5,
      inProgress: 5,
      inReview: 2,
      blocked: 1,
      done: 7,
      backlog: 4,
      cancelled: 1,
    },
    openPrs: 3,
    mergedPrs: 2,
  },
  {
    id: "p2",
    key: "EM",
    name: "زیرساخت مانیتورینگ",
    description: "سیستم مانیتورینگ و هشداردهی زیرساخت",
    status: "planning",
    health: "on_track",
    targetDate: "2026-12-15",
    owner: members[5],
    teamName: "تیم DevOps",
    progress: 0.1,
    counts: {
      todo: 3,
      inProgress: 1,
      inReview: 0,
      blocked: 0,
      done: 1,
      backlog: 5,
      cancelled: 0,
    },
    openPrs: 0,
    mergedPrs: 1,
  },
];

/* ── Helpers ─────────────────────────────────────────────────── */

export function getProjectByKey(key: string): Project | undefined {
  return projects.find((p) => p.key === key.toUpperCase());
}

export function getIssuesByProject(projectKey: string): Issue[] {
  return issues.filter((i) => i.key.startsWith(`${projectKey.toUpperCase()}-`));
}

export function getMilestonesByProject(_projectKey: string): Milestone[] {
  return milestones;
}

export function getCyclesByProject(_projectKey: string): Cycle[] {
  return cycles;
}

export function getActiveCycleByProject(projectKey: string): Cycle | undefined {
  return cycles.find((c) => c.status === "active");
}

export function getPullRequestsByProject(_projectKey: string): PullRequest[] {
  return pullRequests;
}

export function getCommitsByProject(_projectKey: string): Commit[] {
  return commits;
}

export function getActivityByProject(_projectKey: string): ActivityEvent[] {
  return activityEvents;
}

export function getRisksByProject(_projectKey: string): Risk[] {
  return risks;
}

export function getMembersByProject(_projectKey: string): Member[] {
  return members;
}

/** Burndown daily data for the active cycle (fake). */
export function getBurndownData(): { day: string; remaining: number }[] {
  return [
    { day: "۱", remaining: 62 },
    { day: "۲", remaining: 58 },
    { day: "۳", remaining: 55 },
    { day: "۴", remaining: 50 },
    { day: "۵", remaining: 48 },
    { day: "۶", remaining: 46 },
    { day: "۷", remaining: 44 },
    { day: "۸", remaining: 42 },
    { day: "۹", remaining: 40 },
    { day: "۱۰", remaining: 38 },
  ];
}

/* ============================================================
   Canonical MOCK_* aliases (UI contract — Wave 2)
   ============================================================ */
export const MOCK_PROJECTS = projects;
export const MOCK_MEMBERS = members;
export const MOCK_ISSUES = issues;
export const MOCK_MILESTONES = milestones;
export const MOCK_MODULES: { id: string; projectId: string; name: string; description?: string | null }[] = [];
export const MOCK_CYCLES = cycles;
export const MOCK_PULL_REQUESTS = pullRequests;
export const MOCK_COMMITS = commits;
export const MOCK_ACTIVITIES = activityEvents;
export const MOCK_RISKS = risks;
